### ISSUE TITLE
Join to Faker package

### ISSUE THREAD

**Issue by yordis** [GesJeremie/faker-elixir#11]
https://hex.pm/packages/faker and this package have pretty much the same propose. Speaking from my experiences in another ecosystem like `Node` and `Ruby`, it's really painful when you have that many "duplicate in term of propose of the package" We hurts ourself doing these practices.

Anyway, because this is a long conversation.

As today https://hex.pm/packages/faker is the most popular and used on `hex` so I would love to this package integrate with `faker` https://github.com/igas/faker if there is not problem with @GesJeremie and @igas, for the good of the whole community it's better to join forces, resource and time rather than split it up. So both of you don't have to deal with releases, updates, feedbacks, PRs and so on by your own.

I would @igas to see if you can get some work together on what @GesJeremie have and you have on `faker` 🙏 

I love diversity as much you do but when there is big fundamental differences, and even that, I would argue that most of the time is actually separate abstractions and create new architecture rather than just how it's coded

Please @GesJeremie work with @igas on this, and my apologies if I don't understand the differences between both packages because I am talking as an user from `hex`

**Comment by GesJeremie** [comment]
Hey @yordis, I did contribute a bit to Faker: https://github.com/igas/faker/commits?author=GesJeremie. 

To be honest I created this repository because I didn't like how @igas moved the documentation I wrote from the README to another page – A very childish move. 

The foundations are quite different (how we handle translations, etc ..) and I don't really know how we could "merge". That being said, I totally agree with the following:

> We hurts ourself doing these practices.

**Comment by yordis** [comment]
@igas @GesJeremie are you willing to try to tackle which ever problem exist in the pass? 🙏 

As Engineers, we have different opinions but we definitely could find either `data` driven decisions with performance testing for example, or `personal` driven decision where we could relay on some survey on active users or something completely outside of any ego from our nature.
