### ISSUE TITLE
Option to generate only unique data

### ISSUE THREAD

**Issue by ghost** [GesJeremie/faker-elixir#3]
It'd be really great if FakerElixir had a way to generate unique data. This is really useful when certain fields in your mock object require uniqueness to be valid. Basically, if you have this requirement, your test will randomly fail based on whether the data generated for that unique field was actually unique.

Not really sure if it is relevant to this library, since it's more related to mock-ups than generating data.

**Comment by GesJeremie** [comment]
Hi, thanks for the issue!

I thought about it, I don't know yet what will be the best way to handle that. If you have any ideas of the "concept" I will make something.

Right now, what you could do is quite simple:

``` elixir
stream = Stream.repeatedly(fn -> FakerElixir.Internet.email end)

# Let's grab 400 emails
emails = stream |> Enum.take(400)

# Filter them to be unique
filtered = emails |> Enum.uniq
```

When you have your emails filtered you could use the helper cycle to seed your database like a cool guy:

``` elixir
# https://hexdocs.pm/faker_elixir_octopus/FakerElixir.Helper.html#cycle/2
FakerElixir.Helper.cycle(:emails, filtered)
```

The downside is ... you need to have your full dataset before to seed the db. Let me some days and I will set a new version with the unique() helper, at the end I think I found a way ;)

**Comment by GesJeremie** [comment]
@cjhowe https://hexdocs.pm/faker_elixir_octopus/FakerElixir.Helper.html#unique!/2, have fun :)
