### ISSUE TITLE
Possible misconception of Date

### ISSUE THREAD

**Issue by Loschcode** [GesJeremie/faker-elixir#5]
Hi,

Very good library. I wanted to use `FakerElixir.Date` for my project and realized there's no distinction between `Time`, `Date` and `DateTime` ; maybe you could improve this part ?

`Time` would be a real time
`Date` would be a strict date
`DateTime` would be a date with a time

Right now there's only a `Date` and sounds more like a `DateTime` to me.

**Comment by GesJeremie** [comment]
As you pointed out: 

```
FakerElixir.Date.backward(1) # "2016-08-18 05:58:04Z"
```

FakerElixir returns only strings ("fake" date time with UTC) and I want to keep it that way. I guess you are dealing with Ecto, you will be able to cast that string with the functions of the library such as:
-  https://hexdocs.pm/ecto/Ecto.DateTime.html#cast/1
- https://hexdocs.pm/ecto/Ecto.Date.html#cast/1

**Comment by Loschcode** [comment]
You little bitch
