### ISSUE TITLE
Tests not running properly

### ISSUE THREAD

**Issue by Loschcode** [GesJeremie/faker-elixir#6]
I was trying to run my tests with `mix test` and it outputs this strange error

`** (Mix) Could not start application faker_elixir_octopus: could not find application file: faker_elixir_octopus.app
`

I suspect something went wrong with Faker Elixir, do you have any lead on the matter ?

**Comment by GesJeremie** [comment]
Update the **dep** of your mix file to have `:test` too

```
  [{:faker_elixir_octopus, "> 0.0.0",  only: [:dev, :test]}]
```
