### ISSUE TITLE
Start application in seeds (or test)

### ISSUE THREAD

**Issue by hl** [GesJeremie/faker-elixir#7]
Thanks for this great package. One side note, you don't need to add `:faker_elixir_octopus` to your application if you're only going to use it in seeds or tests.

#### Example

```elixir
# seeds.exs
Application.start(:faker_elixir_octopus)
```

or

```elixir
# test_helper.exs
Application.start(:faker_elixir_octopus)
```

**Comment by GesJeremie** [comment]
Update the README and send me a PR, I will be happy to accept it!
